package com.hdd.shiro_demo.dao;

import com.hdd.shiro_demo.domain.UPermission;
import com.hdd.shiro_demo.domain.UPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int countByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int deleteByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int insert(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int insertSelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    List<UPermission> selectByExample(UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    UPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UPermission record, @Param("example") UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UPermission record, @Param("example") UPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UPermission record);
}