package com.hdd.shiro_demo.dao;

import com.hdd.shiro_demo.domain.URole;
import com.hdd.shiro_demo.domain.URoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface URoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int countByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int deleteByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int insert(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int insertSelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    List<URole> selectByExample(URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    URole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") URole record, @Param("example") URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") URole record, @Param("example") URoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(URole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(URole record);
}