package com.hdd.shiro_demo.domain;

public class URolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.rid
     *
     * @mbggenerated
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_role_permission.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.rid
     *
     * @return the value of u_role_permission.rid
     *
     * @mbggenerated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.rid
     *
     * @param rid the value for u_role_permission.rid
     *
     * @mbggenerated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_role_permission.pid
     *
     * @return the value of u_role_permission.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_role_permission.pid
     *
     * @param pid the value for u_role_permission.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }
}