package com.hdd.shiro_demo.domain;

public class UUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_user_role.rid
     *
     * @mbggenerated
     */
    private Long rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.uid
     *
     * @return the value of u_user_role.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.uid
     *
     * @param uid the value for u_user_role.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_user_role.rid
     *
     * @return the value of u_user_role.rid
     *
     * @mbggenerated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_user_role.rid
     *
     * @param rid the value for u_user_role.rid
     *
     * @mbggenerated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }
}